version: '3'
#all port number should be exposed appending 9
services:

  nginx:
    image: zesticio/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "6443:443"
    volumes:
      - ${DATA}/nginx/config:/etc/nginx
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true
