version: '3'
#all port number should be exposed appending 9
services:

  nginx:
    image: zesticio/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "6443:443"
    volumes:
      - ${DATA}/nginx/config:/etc/nginx
    networks:
      - portainer

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ${DATA}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: KeycloakDB
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

networks:
  portainer:
    name: portainer
    external: true
