version: '3.9'
#all port number should be exposed appending 9
services:

  authy-nginx:
    image: nginx
    container_name: authy-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "9080:9080"
    depends_on:
      - keycloak
    networks:
      - backend

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    restart: unless-stopped
    env_file:
      - ./keycloak.dev.env
    volumes:
      - ./keycloak/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - authy-postgres
    networks:
      - backend

  authy-app:
    container_name: authy-app
    depends_on:
      - keycloak
    image: zesticsolutions/authy:latest
    restart: unless-stopped
    volumes:
      - /zestic/authy/app:/opt/service/config
    networks:
      - backend

  authy-postgres:
    image: postgres
    container_name: authy-postgres
    restart: always
    env_file:
      - ./database.dev.env
    volumes:
      - /zestic/authy/postgres:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakrw
    networks:
      - backend

  authy-pgadmin:
    container_name: authy-pgadmin
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./database.dev.env
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge