version: '3.4'
#all port number should be exposed appending 9
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www:/usr/share/nginx/html
    ports:
      - "9080:9080"
    depends_on:
      - keycloak
    networks:
      - zestic.internal

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /zestic/authy/postgres:/var/lib/postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakrw
    networks:
      - zestic.internal

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    restart: unless-stopped
    volumes:
      - ./keycloak/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DEBUGGING=1
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_STATISTICS=all
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - DB_SCHEMA=public
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KC_METRICS_ENABLED=true
    depends_on:
      - postgres
    networks:
      - zestic.internal

  authy:
    container_name: app
    depends_on:
      - keycloak
    image: zesticsolutions/authy:latest
    restart: unless-stopped
    volumes:
      - /zestic/authy/app:/opt/service/config
    networks:
      - zestic.internal
      - zestic.external

networks:
  zestic.internal:
    external: true
  zestic.external:
    external: true
