version: '3'
#all port number should be exposed appending 9
services:

  keycloak:
    container_name: authy-keycloak
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DEBUGGING=1
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - KEYCLOAK_LOGLEVEL=INFO
    ports:
      - "9080:8080"
    networks:
      - zestic.internal
      - zestic.external
      - overnet #between host

  authy:
    container_name: authy-app
    depends_on:
      - keycloak
    image: zesticsolutions/authy:latest
    restart: unless-stopped
    volumes:
      - /zestic/authy/app:/opt/service/config
#    environment:
#      JAVA_OPTS: -Dspring.config.location=/zestic/authy/app/application.properties -Dlog4j.configuration=file:////zestic/authy/app/log4j.properties
    ports:
      - "9090:9090"
    networks:
      - zestic.internal
      - zestic.external
      - overnet #between host

networks:
  zestic.internal:
    external: true
  zestic.external:
    external: true
  overnet:
    external: true
    driver: overlay
