version: '3.4'
#all port number should be exposed appending 9
services:

  postgres:
    image: postgres
    container_name: authy-postgres
    restart: always
    volumes:
      - /zestic/authy/postgres:/var/lib/postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakrw
    networks:
      - zestic.internal

  keycloak:
    container_name: authy-keycloak
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    restart: unless-stopped
    volumes:
      - /zestic/authy/keycloak/:/opt/jboss/
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DEBUGGING=1
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - KEYCLOAK_LOGLEVEL=INFO
    ports:
      - "9080:8080"
    networks:
      - zestic.internal

  authy:
    container_name: authy-app
    depends_on:
      - keycloak
    image: zesticsolutions/authy:latest
    restart: unless-stopped
    volumes:
      - /zestic/authy/app:/opt/service/config
    ports:
      - "9090:9090"
    networks:
      - zestic.internal
      - zestic.external

networks:
  zestic.internal:
    external: true
  zestic.external:
    external: true
