version: '3'
#all port number should be exposed appending 9
services:

  postgres:
    image: postgres
    container_name: authy-postgres
    restart: always
    volumes:
      - /zestic/authy/postgres:/var/lib/postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakrw
    networks:
      - keycloak-internal

  keycloak-service:
    container_name: authy-keycloak
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - KEYCLOAK_LOGLEVEL=INFO
    ports:
      - "9080:8080"
    networks:
      - keycloak-internal
      - zestic.external

networks:
  keycloak-internal:
  zestic.external:
    external: true