version: '3.9'
#all port number should be exposed appending 9
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "9080:9080"
    depends_on:
      - keycloak
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0-legacy
    env_file:
      - ./keycloak.dev.env
    volumes:
      - ./keycloak/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
    networks:
      - keycloak

  postgres:
    image: postgres
    env_file:
      - ./database.dev.env
    volumes:
      - /zestic/authy/postgres:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakrw
    networks:
      - keycloak

  pgadmin:
    image: "dpage/pgadmin4:5.1"
    env_file:
      - ./database.dev.env
    depends_on:
      - postgres
    networks:
      - keycloak

  app:
    depends_on:
      - keycloak
    image: zesticsolutions/authy:latest
    volumes:
      - /zestic/authy/app:/opt/service/config
    networks:
      - keycloak

networks:
  keycloak:
    external: true