version: '3'
#all port number should be exposed appending 9
services:

  keycloak-service:
    container_name: authy-keycloak
    depends_on:
      - mariadb
    image: quay.io/keycloak/keycloak:legacy
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakrw
      - KEYCLOAK_LOGLEVEL=ERROR
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "9080:8080"
    volumes:
      - /zestic/authy/keycloak:/opt/jboss
    networks:
      - keycloak-internal
      - zestic.external

  mariadb:
    image: mariadb
    container_name: authy-mariadb
    restart: unless-stopped
    volumes:
      - /zestic/authy/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MARIADB
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakrw
      MYSQL_DATABASE: keycloak
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    networks:
      - keycloak-internal

networks:
  keycloak-internal:
  zestic.external:
    external: true