version: '3'
#all port number should be exposed appending 9
services:

  nginx:
    image: zesticio/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "9080:80"
      - "9443:443"
    networks:
      - keycloak

#  keycloak:
#    image: quay.io/keycloak/keycloak:17.0.0-legacy
#    restart: always
#    env_file:
#      - ./keycloak.env
#    volumes:
#      - ./keycloak/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties
#    ports:
#      - "9990:9990"
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"
#    depends_on:
#      - postgres
#    networks:
#      - keycloak
#
#  postgres:
#    image: postgres
#    restart: always
#    env_file:
#      - ./database.env
#    volumes:
#      - /zestic/authy/postgres:/var/lib/postgresql/data/
#      - ./sql:/docker-entrypoint-initdb.d/:ro
#    networks:
#      - keycloak

#  app:
#    image: zesticsolutions/authy:latest
#    restart: always
#    volumes:
#      - /zestic/authy/app:/opt/service/config
#    depends_on:
#      - keycloak
#    networks:
#      - keycloak

networks:
  keycloak:
    name: keycloak
    external: true
