name: Deploy to artifactory

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java SDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Build with Maven
        run: mvn --settings settings.xml --file pom.xml install
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
